apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaConnector
metadata:
  name: kafka-datagen-json
  labels:
    eventstreams.ibm.com/cluster: kafka-connect-cluster
spec:
  class: com.ibm.eventautomation.demos.loosehangerjeans.DatagenSourceConnector
  tasksMax: 1
  config:
    key.converter: org.apache.kafka.connect.storage.StringConverter
    key.converter.schemas.enable: false
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false

    topic.name.orders: ORDERS.NEW.JSON
    topic.name.cancellations: CANCELLATIONS.JSON
    topic.name.stockmovements: STOCK.MOVEMENT.JSON
    topic.name.badgeins: DOOR.BADGEIN.JSON
    topic.name.newcustomers: CUSTOMERS.NEW.JSON
    topic.name.sensorreadings: SENSOR.READINGS.JSON