apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaConnect
metadata:
  name: kafka-connect-cluster
  annotations:
    eventstreams.ibm.com/use-connector-resources: 'true'
spec:
  build:
    output:
      image: image-registry.openshift-image-registry.svc:5000/event-automation/xml-processing-demo:0.0.1
      type: docker
    plugins:
      - name: xml-converter
        artifacts:
          - type: jar
            url: https://github.com/IBM-messaging/kafka-connect-xml-converter/releases/download/0.1.0/kafka-connect-xml-converter-0.1.0-jar-with-dependencies.jar
      - name: datagen
        artifacts:
          - type: jar
            url: https://github.com/IBM/kafka-connect-loosehangerjeans-source/releases/download/0.0.4/kafka-connect-loosehangerjeans-source-0.0.4-jar-with-dependencies.jar
      - name: http
        artifacts:
          - type: zip
            url: https://github.com/Aiven-Open/http-connector-for-apache-kafka/releases/download/v0.7.0/http-connector-for-apache-kafka-0.7.0.zip
      - name: stock-prices
        artifacts:
          - type: jar
            url: https://github.com/dalelane/kafka-connect-stockprice-source/releases/download/v0.0.3/kafka-connect-stockprice-source-connector.jar
      - name: mq-source
        artifacts:
          - type: jar
            url: https://github.com/ibm-messaging/kafka-connect-mq-source/releases/download/v1.3.4/kafka-connect-mq-source-1.3.4-jar-with-dependencies.jar
      - name: mq-sink
        artifacts:
          - type: jar
            url: https://github.com/ibm-messaging/kafka-connect-mq-sink/releases/download/v1.5.2/kafka-connect-mq-sink-1.5.2-jar-with-dependencies.jar
      - name: weather
        artifacts:
          - artifact: camel-weather-kafka-connector
            group: org.apache.camel.kafkaconnector
            type: maven
            version: 0.11.5
      - name: apicurio
        artifacts:
          - artifact: apicurio-registry-serdes-avro-serde
            group: io.apicurio
            type: maven
            version: 2.5.5.Final
          - artifact: apicurio-registry-utils-converter
            group: io.apicurio
            type: maven
            version: 2.5.5.Final
      - name: confluent
        artifacts:
          - type: maven
            repository: https://packages.confluent.io/maven/
            group: io.confluent
            artifact: kafka-connect-avro-converter
            version: 7.5.1
  externalConfiguration:
    volumes:
      - name: weather
        secret:
          secretName: weather
      - name: alphavantage
        secret:
          secretName: alphavantage
      - configMap:
          name: xml-schemas
        name: xml-schemas
  config:
    client.id: kafka-connect-client
    group.id: kafka-connect
    config.storage.topic: connect-configs
    offset.storage.topic: connect-offsets
    status.storage.topic: connect-status
    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.DirectoryConfigProvider
  bootstrapServers: 'my-kafka-cluster-kafka-bootstrap.event-automation.svc:9095'
  resources:
    limits:
      cpu: 2048m
      memory: 2Gi
    requests:
      cpu: 2048m
      memory: 2Gi
  authentication:
    passwordSecret:
      password: password
      secretName: kafka-connect-credentials
    type: scram-sha-512
    username: kafka-connect-credentials
  template:
    buildConfig:
      pullSecret: ibm-entitlement-key
    connectContainer:
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
    pod:
      imagePullSecrets: []
      metadata:
        annotations:
          cloudpakId: c8b82d189e7545f0892db9ef2731b90d
          productVersion: 11.2.5
          productID: 2a79e49111f44ec3acd89608e56138f5
          cloudpakName: IBM Cloud Pak for Integration
          productChargedContainers: kafka-connect-cluster-connect
          productCloudpakRatio: '2:1'
          productName: IBM Event Streams for Non Production
          eventstreams.production.type: CloudPakForIntegrationNonProduction
          productMetric: VIRTUAL_PROCESSOR_CORE
  tls:
    trustedCertificates:
      - certificate: ca.crt
        secretName: my-kafka-cluster-cluster-ca-cert
  replicas: 1
