apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaConnector
metadata:
  name: mq-xml-to-avro-apicurio
  labels:
    eventstreams.ibm.com/cluster: kafka-connect-cluster
spec:
  class: com.ibm.eventstreams.connect.mqsource.MQSourceConnector
  tasksMax: 1
  config:
    # the Kafka topic to produce to
    topic: XML.MESSAGES.2

    # the MQ queue to get messages from
    mq.queue: XML.MESSAGES.2

    # connection details for the queue manager
    mq.queue.manager: MYQMGR
    mq.connection.name.list: queuemanager-ibm-mq(1414)
    mq.channel.name: KAFKA.SVRCONN

    # format of the messages being parsed
    mq.message.body.jms: true
    mq.record.builder: com.ibm.eventstreams.kafkaconnect.plugins.xml.XmlMQRecordBuilder
    mq.record.builder.root.element.name: simple
    mq.record.builder.xsd.schema.path: /opt/kafka/external-configuration/xml-schemas/simple.xsd

    # format of the messages to produce
    key.converter: org.apache.kafka.connect.storage.StringConverter
    key.converter.schemas.enable: false
    value.converter: io.apicurio.registry.utils.converter.AvroConverter
    value.converter.schemas.enable: true

    # connection details for the schema registry to use
    value.converter.apicurio.registry.url: https://kafka-connect-credentials:${file:/opt/kafka/connect-password/kafka-connect-credentials:password}@my-kafka-cluster-ibm-es-ac-reg-external-event-automation.apps.dalelane.cp.fyre.ibm.com
    value.converter.apicurio.auth.username: kafka-connect-credentials
    value.converter.apicurio.auth.password: ${file:/opt/kafka/connect-password/kafka-connect-credentials:password}
    value.converter.apicurio.registry.request.ssl.truststore.type: PKCS12
    value.converter.apicurio.registry.request.ssl.truststore.location: /opt/kafka/connect-certs/my-kafka-cluster-cluster-ca-cert/ca.p12
    value.converter.apicurio.registry.request.ssl.truststore.password: ${file:/opt/kafka/connect-certs/my-kafka-cluster-cluster-ca-cert:ca.password}

    # config for use of the schema registry
    value.converter.apicurio.registry.global-id: io.apicurio.registry.utils.serde.strategy.GetOrCreateIdStrategy
    value.converter.apicurio.registry.auto-register: true
